name: ci

on:
  push:
    branches:
      - 'production'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: https://registry.ellite.dev/
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: raibu-web:latest
