name: Push to registry

on:
  push:
    branches:
      - "production"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: http://registry.ellite.dev/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: registry.ellite.dev/raibu-web:latest
      - name: Test image
        run: |
          docker pull registry.ellite.dev/raibu-web:latest
          if [ $? -eq 0 ]; then
            echo "Image exists"
          else
            echo "Image does not exist"
            exit 1
          fi
  tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List file permissions
        run: ls -l
      - name: Create tarball
        run: |
          tar --warning=no-file-changed --exclude='./.git' -czvf raibu-web.tar.gz .
      - name: Upload tarball
        uses: actions/upload-artifact@v2
        with:
          name: raibu-web
          path: raibu-web.tar.gz
