name: Push to registry

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: http://registry.ellite.dev/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prepare Docker Image Tag
        id: prep
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//''}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.ellite.dev/raibu-web:${{ steps.prep.outputs.tag }}, registry.ellite.dev/raibu-web:latest
          build-args: |
            PUBLIC_RAIBU_URL==${{ secrets.PUBLIC_RAIBU_URL }}
            RAIBU_DB_URL=${{ secrets.RAIBU_DB_URL }}
            RAIBU_EMAIL_HOST=${{ secrets.RAIBU_EMAIL_HOST }}
            RAIBU_EMAIL_PORT=${{ secrets.RAIBU_EMAIL_PORT }}
            RAIBU_EMAIL_USER=${{ secrets.RAIBU_EMAIL_USER }}
            RAIBU_EMAIL_PASS=${{ secrets.RAIBU_EMAIL_PASS }}
            RAIBU_ADMIN_PASS=${{ secrets.RAIBU_ADMIN_PASS }}
            RAIBU_IP_GEOLOCATION_API_KEY=${{ secrets.RAIBU_IP_GEOLOCATION_API_KEY }}
            RAIBU_BRAINTREE_MERCHANT_ID=${{ secrets.RAIBU_BRAINTREE_MERCHANT_ID }}
            RAIBU_BRAINTREE_PUBLIC_KEY=${{ secrets.RAIBU_BRAINTREE_PUBLIC_KEY }}
            RAIBU_BRAINTREE_PRIVATE_KEY=${{ secrets.RAIBU_BRAINTREE_PRIVATE_KEY }}
      - name: Test image
        run: |
          docker pull registry.ellite.dev/raibu-web:${{ steps.prep.outputs.tag }}
          if [ $? -eq 0 ]; then
            echo "Image exists"
          else
            echo "Image does not exist"
            exit 1
          fi
      - name: Send POST request to Portainer
        run: |
          curl -X POST https://portainer.ellite.dev/api/stacks/webhooks/4670c0f8-1ef1-4d9e-8a81-f4c3a1c70c45

  tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create copy of workspace
        run: |
          mkdir ../temp_workspace
          cp -r . ../temp_workspace
      - name: Create tarball
        run: |
          tar --exclude='./.git' -czvvf raibu-web.tar.gz ../temp_workspace
      - name: Upload tarball
        uses: actions/upload-artifact@v2
        with:
          name: raibu-web
          path: raibu-web.tar.gz
